/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace DataTypes {
  export type ConfirmationStruct = {
    ruling: PromiseOrValue<string>;
    evidence: PromiseOrValue<boolean>;
    witness: PromiseOrValue<BigNumberish>;
  };

  export type ConfirmationStructOutput = [string, boolean, BigNumber] & {
    ruling: string;
    evidence: boolean;
    witness: BigNumber;
  };

  export type RepChangeStruct = {
    domain: PromiseOrValue<string>;
    value: PromiseOrValue<BigNumberish>;
    disabled: PromiseOrValue<boolean>;
  };

  export type RepChangeStructOutput = [string, BigNumber, boolean] & {
    domain: string;
    value: BigNumber;
    disabled: boolean;
  };

  export type RuleStruct = {
    about: PromiseOrValue<BytesLike>;
    affected: PromiseOrValue<string>;
    negation: PromiseOrValue<boolean>;
    uri: PromiseOrValue<string>;
    disabled: PromiseOrValue<boolean>;
  };

  export type RuleStructOutput = [string, string, boolean, string, boolean] & {
    about: string;
    affected: string;
    negation: boolean;
    uri: string;
    disabled: boolean;
  };
}

export interface RuleRepoInterface extends utils.Interface {
  functions: {
    "confirmationGet(uint256)": FunctionFragment;
    "effectsGet(uint256)": FunctionFragment;
    "effectsGetOf(address,uint256)": FunctionFragment;
    "getRepoAddr()": FunctionFragment;
    "ruleAdd((bytes32,string,bool,string,bool),(string,bool,uint256),(string,int256,bool)[])": FunctionFragment;
    "ruleConfirmationUpdate(uint256,(string,bool,uint256))": FunctionFragment;
    "ruleDisable(uint256,bool)": FunctionFragment;
    "ruleGet(uint256)": FunctionFragment;
    "ruleUpdate(uint256,(bytes32,string,bool,string,bool),(string,int256,bool)[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "confirmationGet"
      | "effectsGet"
      | "effectsGetOf"
      | "getRepoAddr"
      | "ruleAdd"
      | "ruleConfirmationUpdate"
      | "ruleDisable"
      | "ruleGet"
      | "ruleUpdate"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "confirmationGet",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "effectsGet",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "effectsGetOf",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRepoAddr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ruleAdd",
    values: [
      DataTypes.RuleStruct,
      DataTypes.ConfirmationStruct,
      DataTypes.RepChangeStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "ruleConfirmationUpdate",
    values: [PromiseOrValue<BigNumberish>, DataTypes.ConfirmationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "ruleDisable",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "ruleGet",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "ruleUpdate",
    values: [
      PromiseOrValue<BigNumberish>,
      DataTypes.RuleStruct,
      DataTypes.RepChangeStruct[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "confirmationGet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "effectsGet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "effectsGetOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRepoAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ruleAdd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ruleConfirmationUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ruleDisable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ruleGet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ruleUpdate", data: BytesLike): Result;

  events: {
    "Claim(address,uint256,bytes32)": EventFragment;
    "Confirmation(address,uint256,string,bool,uint256)": EventFragment;
    "Rule(address,uint256,bytes32,string,string,bool)": EventFragment;
    "RuleDisabled(address,uint256,bool)": EventFragment;
    "RuleEffect(address,uint256,string,int256)": EventFragment;
    "RuleRemoved(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Claim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Confirmation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Rule"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RuleDisabled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RuleEffect"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RuleRemoved"): EventFragment;
}

export interface ClaimEventObject {
  originAddress: string;
  id: BigNumber;
  claimId: string;
}
export type ClaimEvent = TypedEvent<
  [string, BigNumber, string],
  ClaimEventObject
>;

export type ClaimEventFilter = TypedEventFilter<ClaimEvent>;

export interface ConfirmationEventObject {
  originAddress: string;
  id: BigNumber;
  ruling: string;
  evidence: boolean;
  witness: BigNumber;
}
export type ConfirmationEvent = TypedEvent<
  [string, BigNumber, string, boolean, BigNumber],
  ConfirmationEventObject
>;

export type ConfirmationEventFilter = TypedEventFilter<ConfirmationEvent>;

export interface RuleEventObject {
  originAddress: string;
  id: BigNumber;
  about: string;
  affected: string;
  uri: string;
  negation: boolean;
}
export type RuleEvent = TypedEvent<
  [string, BigNumber, string, string, string, boolean],
  RuleEventObject
>;

export type RuleEventFilter = TypedEventFilter<RuleEvent>;

export interface RuleDisabledEventObject {
  originAddress: string;
  id: BigNumber;
  disabled: boolean;
}
export type RuleDisabledEvent = TypedEvent<
  [string, BigNumber, boolean],
  RuleDisabledEventObject
>;

export type RuleDisabledEventFilter = TypedEventFilter<RuleDisabledEvent>;

export interface RuleEffectEventObject {
  originAddress: string;
  id: BigNumber;
  domain: string;
  value: BigNumber;
}
export type RuleEffectEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  RuleEffectEventObject
>;

export type RuleEffectEventFilter = TypedEventFilter<RuleEffectEvent>;

export interface RuleRemovedEventObject {
  originAddress: string;
  id: BigNumber;
}
export type RuleRemovedEvent = TypedEvent<
  [string, BigNumber],
  RuleRemovedEventObject
>;

export type RuleRemovedEventFilter = TypedEventFilter<RuleRemovedEvent>;

export interface RuleRepo extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RuleRepoInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    confirmationGet(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[DataTypes.ConfirmationStructOutput]>;

    effectsGet(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[DataTypes.RepChangeStructOutput[]]>;

    effectsGetOf(
      ownerAddress: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[DataTypes.RepChangeStructOutput[]]>;

    getRepoAddr(overrides?: CallOverrides): Promise<[string]>;

    ruleAdd(
      rule: DataTypes.RuleStruct,
      confirmation: DataTypes.ConfirmationStruct,
      effects: DataTypes.RepChangeStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ruleConfirmationUpdate(
      id: PromiseOrValue<BigNumberish>,
      confirmation: DataTypes.ConfirmationStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ruleDisable(
      id: PromiseOrValue<BigNumberish>,
      disabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ruleGet(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[DataTypes.RuleStructOutput]>;

    ruleUpdate(
      id: PromiseOrValue<BigNumberish>,
      rule: DataTypes.RuleStruct,
      effects: DataTypes.RepChangeStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  confirmationGet(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<DataTypes.ConfirmationStructOutput>;

  effectsGet(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<DataTypes.RepChangeStructOutput[]>;

  effectsGetOf(
    ownerAddress: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<DataTypes.RepChangeStructOutput[]>;

  getRepoAddr(overrides?: CallOverrides): Promise<string>;

  ruleAdd(
    rule: DataTypes.RuleStruct,
    confirmation: DataTypes.ConfirmationStruct,
    effects: DataTypes.RepChangeStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ruleConfirmationUpdate(
    id: PromiseOrValue<BigNumberish>,
    confirmation: DataTypes.ConfirmationStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ruleDisable(
    id: PromiseOrValue<BigNumberish>,
    disabled: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ruleGet(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<DataTypes.RuleStructOutput>;

  ruleUpdate(
    id: PromiseOrValue<BigNumberish>,
    rule: DataTypes.RuleStruct,
    effects: DataTypes.RepChangeStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    confirmationGet(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<DataTypes.ConfirmationStructOutput>;

    effectsGet(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<DataTypes.RepChangeStructOutput[]>;

    effectsGetOf(
      ownerAddress: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<DataTypes.RepChangeStructOutput[]>;

    getRepoAddr(overrides?: CallOverrides): Promise<string>;

    ruleAdd(
      rule: DataTypes.RuleStruct,
      confirmation: DataTypes.ConfirmationStruct,
      effects: DataTypes.RepChangeStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ruleConfirmationUpdate(
      id: PromiseOrValue<BigNumberish>,
      confirmation: DataTypes.ConfirmationStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    ruleDisable(
      id: PromiseOrValue<BigNumberish>,
      disabled: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    ruleGet(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<DataTypes.RuleStructOutput>;

    ruleUpdate(
      id: PromiseOrValue<BigNumberish>,
      rule: DataTypes.RuleStruct,
      effects: DataTypes.RepChangeStruct[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Claim(address,uint256,bytes32)"(
      originAddress?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null,
      claimId?: null
    ): ClaimEventFilter;
    Claim(
      originAddress?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null,
      claimId?: null
    ): ClaimEventFilter;

    "Confirmation(address,uint256,string,bool,uint256)"(
      originAddress?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null,
      ruling?: null,
      evidence?: null,
      witness?: null
    ): ConfirmationEventFilter;
    Confirmation(
      originAddress?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null,
      ruling?: null,
      evidence?: null,
      witness?: null
    ): ConfirmationEventFilter;

    "Rule(address,uint256,bytes32,string,string,bool)"(
      originAddress?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null,
      about?: null,
      affected?: null,
      uri?: null,
      negation?: null
    ): RuleEventFilter;
    Rule(
      originAddress?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null,
      about?: null,
      affected?: null,
      uri?: null,
      negation?: null
    ): RuleEventFilter;

    "RuleDisabled(address,uint256,bool)"(
      originAddress?: PromiseOrValue<string> | null,
      id?: null,
      disabled?: null
    ): RuleDisabledEventFilter;
    RuleDisabled(
      originAddress?: PromiseOrValue<string> | null,
      id?: null,
      disabled?: null
    ): RuleDisabledEventFilter;

    "RuleEffect(address,uint256,string,int256)"(
      originAddress?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null,
      domain?: null,
      value?: null
    ): RuleEffectEventFilter;
    RuleEffect(
      originAddress?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null,
      domain?: null,
      value?: null
    ): RuleEffectEventFilter;

    "RuleRemoved(address,uint256)"(
      originAddress?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null
    ): RuleRemovedEventFilter;
    RuleRemoved(
      originAddress?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null
    ): RuleRemovedEventFilter;
  };

  estimateGas: {
    confirmationGet(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    effectsGet(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    effectsGetOf(
      ownerAddress: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRepoAddr(overrides?: CallOverrides): Promise<BigNumber>;

    ruleAdd(
      rule: DataTypes.RuleStruct,
      confirmation: DataTypes.ConfirmationStruct,
      effects: DataTypes.RepChangeStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ruleConfirmationUpdate(
      id: PromiseOrValue<BigNumberish>,
      confirmation: DataTypes.ConfirmationStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ruleDisable(
      id: PromiseOrValue<BigNumberish>,
      disabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ruleGet(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ruleUpdate(
      id: PromiseOrValue<BigNumberish>,
      rule: DataTypes.RuleStruct,
      effects: DataTypes.RepChangeStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    confirmationGet(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    effectsGet(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    effectsGetOf(
      ownerAddress: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRepoAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ruleAdd(
      rule: DataTypes.RuleStruct,
      confirmation: DataTypes.ConfirmationStruct,
      effects: DataTypes.RepChangeStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ruleConfirmationUpdate(
      id: PromiseOrValue<BigNumberish>,
      confirmation: DataTypes.ConfirmationStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ruleDisable(
      id: PromiseOrValue<BigNumberish>,
      disabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ruleGet(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ruleUpdate(
      id: PromiseOrValue<BigNumberish>,
      rule: DataTypes.RuleStruct,
      effects: DataTypes.RepChangeStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
