/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace DataTypes {
  export type ConditionStruct = {
    repo: PromiseOrValue<string>;
    id: PromiseOrValue<BytesLike>;
  };

  export type ConditionStructOutput = [string, string] & {
    repo: string;
    id: string;
  };

  export type ConfirmationStruct = {
    ruling: PromiseOrValue<string>;
    evidence: PromiseOrValue<boolean>;
    witness: PromiseOrValue<BigNumberish>;
  };

  export type ConfirmationStructOutput = [string, boolean, BigNumber] & {
    ruling: string;
    evidence: boolean;
    witness: BigNumber;
  };

  export type RepChangeStruct = {
    domain: PromiseOrValue<string>;
    value: PromiseOrValue<BigNumberish>;
    disabled: PromiseOrValue<boolean>;
  };

  export type RepChangeStructOutput = [string, BigNumber, boolean] & {
    domain: string;
    value: BigNumber;
    disabled: boolean;
  };

  export type RuleStruct = {
    about: PromiseOrValue<BytesLike>;
    affected: PromiseOrValue<string>;
    negation: PromiseOrValue<boolean>;
    uri: PromiseOrValue<string>;
    disabled: PromiseOrValue<boolean>;
  };

  export type RuleStructOutput = [string, string, boolean, string, boolean] & {
    about: string;
    affected: string;
    negation: boolean;
    uri: string;
    disabled: boolean;
  };
}

export interface IRulesRepoInterface extends utils.Interface {
  functions: {
    "conditionsGet(uint256)": FunctionFragment;
    "conditionsGetOf(address,uint256)": FunctionFragment;
    "confirmationGet(uint256)": FunctionFragment;
    "confirmationGetOf(address,uint256)": FunctionFragment;
    "effectsGet(uint256)": FunctionFragment;
    "effectsGetOf(address,uint256)": FunctionFragment;
    "ruleAdd((bytes32,string,bool,string,bool),(string,int256,bool)[],(string,bool,uint256))": FunctionFragment;
    "ruleDisable(uint256,bool)": FunctionFragment;
    "ruleEffectsUpdate(uint256,(string,int256,bool)[])": FunctionFragment;
    "ruleGet(uint256)": FunctionFragment;
    "ruleUpdateConditions(uint256,(string,bytes32)[])": FunctionFragment;
    "ruleUpdateConfirmation(uint256,(string,bool,uint256))": FunctionFragment;
    "ruleUpdateURI(uint256,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "conditionsGet"
      | "conditionsGetOf"
      | "confirmationGet"
      | "confirmationGetOf"
      | "effectsGet"
      | "effectsGetOf"
      | "ruleAdd"
      | "ruleDisable"
      | "ruleEffectsUpdate"
      | "ruleGet"
      | "ruleUpdateConditions"
      | "ruleUpdateConfirmation"
      | "ruleUpdateURI"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "conditionsGet",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "conditionsGetOf",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmationGet",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmationGetOf",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "effectsGet",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "effectsGetOf",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "ruleAdd",
    values: [
      DataTypes.RuleStruct,
      DataTypes.RepChangeStruct[],
      DataTypes.ConfirmationStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "ruleDisable",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "ruleEffectsUpdate",
    values: [PromiseOrValue<BigNumberish>, DataTypes.RepChangeStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "ruleGet",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "ruleUpdateConditions",
    values: [PromiseOrValue<BigNumberish>, DataTypes.ConditionStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "ruleUpdateConfirmation",
    values: [PromiseOrValue<BigNumberish>, DataTypes.ConfirmationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "ruleUpdateURI",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "conditionsGet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "conditionsGetOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmationGet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmationGetOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "effectsGet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "effectsGetOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ruleAdd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ruleDisable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ruleEffectsUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ruleGet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ruleUpdateConditions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ruleUpdateConfirmation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ruleUpdateURI",
    data: BytesLike
  ): Result;

  events: {
    "Condition(address,uint256,string,bytes32)": EventFragment;
    "Confirmation(address,uint256,string,bool,uint256)": EventFragment;
    "RemovedConditions(address,uint256)": EventFragment;
    "RemovedEffects(address,uint256)": EventFragment;
    "Rule(address,uint256,bytes32,string,string,bool)": EventFragment;
    "RuleDisabled(address,uint256,bool)": EventFragment;
    "RuleEffect(address,uint256,string,int256)": EventFragment;
    "RuleRemoved(address,uint256)": EventFragment;
    "RuleURI(address,uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Condition"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Confirmation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemovedConditions"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemovedEffects"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Rule"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RuleDisabled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RuleEffect"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RuleRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RuleURI"): EventFragment;
}

export interface ConditionEventObject {
  originAddress: string;
  ruleId: BigNumber;
  repo: string;
  id: string;
}
export type ConditionEvent = TypedEvent<
  [string, BigNumber, string, string],
  ConditionEventObject
>;

export type ConditionEventFilter = TypedEventFilter<ConditionEvent>;

export interface ConfirmationEventObject {
  originAddress: string;
  ruleId: BigNumber;
  ruling: string;
  evidence: boolean;
  witness: BigNumber;
}
export type ConfirmationEvent = TypedEvent<
  [string, BigNumber, string, boolean, BigNumber],
  ConfirmationEventObject
>;

export type ConfirmationEventFilter = TypedEventFilter<ConfirmationEvent>;

export interface RemovedConditionsEventObject {
  originAddress: string;
  ruleId: BigNumber;
}
export type RemovedConditionsEvent = TypedEvent<
  [string, BigNumber],
  RemovedConditionsEventObject
>;

export type RemovedConditionsEventFilter =
  TypedEventFilter<RemovedConditionsEvent>;

export interface RemovedEffectsEventObject {
  originAddress: string;
  ruleId: BigNumber;
}
export type RemovedEffectsEvent = TypedEvent<
  [string, BigNumber],
  RemovedEffectsEventObject
>;

export type RemovedEffectsEventFilter = TypedEventFilter<RemovedEffectsEvent>;

export interface RuleEventObject {
  originAddress: string;
  ruleId: BigNumber;
  about: string;
  affected: string;
  uri: string;
  negation: boolean;
}
export type RuleEvent = TypedEvent<
  [string, BigNumber, string, string, string, boolean],
  RuleEventObject
>;

export type RuleEventFilter = TypedEventFilter<RuleEvent>;

export interface RuleDisabledEventObject {
  originAddress: string;
  ruleId: BigNumber;
  disabled: boolean;
}
export type RuleDisabledEvent = TypedEvent<
  [string, BigNumber, boolean],
  RuleDisabledEventObject
>;

export type RuleDisabledEventFilter = TypedEventFilter<RuleDisabledEvent>;

export interface RuleEffectEventObject {
  originAddress: string;
  ruleId: BigNumber;
  domain: string;
  value: BigNumber;
}
export type RuleEffectEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  RuleEffectEventObject
>;

export type RuleEffectEventFilter = TypedEventFilter<RuleEffectEvent>;

export interface RuleRemovedEventObject {
  originAddress: string;
  ruleId: BigNumber;
}
export type RuleRemovedEvent = TypedEvent<
  [string, BigNumber],
  RuleRemovedEventObject
>;

export type RuleRemovedEventFilter = TypedEventFilter<RuleRemovedEvent>;

export interface RuleURIEventObject {
  originAddress: string;
  ruleId: BigNumber;
  uri: string;
}
export type RuleURIEvent = TypedEvent<
  [string, BigNumber, string],
  RuleURIEventObject
>;

export type RuleURIEventFilter = TypedEventFilter<RuleURIEvent>;

export interface IRulesRepo extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRulesRepoInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    conditionsGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[DataTypes.ConditionStructOutput[]]>;

    conditionsGetOf(
      ownerAddress: PromiseOrValue<string>,
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[DataTypes.ConditionStructOutput[]]>;

    confirmationGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[DataTypes.ConfirmationStructOutput]>;

    confirmationGetOf(
      ownerAddress: PromiseOrValue<string>,
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[DataTypes.ConfirmationStructOutput]>;

    effectsGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[DataTypes.RepChangeStructOutput[]]>;

    effectsGetOf(
      ownerAddress: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[DataTypes.RepChangeStructOutput[]]>;

    ruleAdd(
      rule: DataTypes.RuleStruct,
      effects: DataTypes.RepChangeStruct[],
      confirmation: DataTypes.ConfirmationStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ruleDisable(
      ruleId: PromiseOrValue<BigNumberish>,
      disabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ruleEffectsUpdate(
      ruleId: PromiseOrValue<BigNumberish>,
      effects: DataTypes.RepChangeStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ruleGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[DataTypes.RuleStructOutput]>;

    ruleUpdateConditions(
      ruleId: PromiseOrValue<BigNumberish>,
      conditions: DataTypes.ConditionStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ruleUpdateConfirmation(
      ruleId: PromiseOrValue<BigNumberish>,
      confirmation: DataTypes.ConfirmationStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ruleUpdateURI(
      ruleId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  conditionsGet(
    ruleId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<DataTypes.ConditionStructOutput[]>;

  conditionsGetOf(
    ownerAddress: PromiseOrValue<string>,
    ruleId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<DataTypes.ConditionStructOutput[]>;

  confirmationGet(
    ruleId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<DataTypes.ConfirmationStructOutput>;

  confirmationGetOf(
    ownerAddress: PromiseOrValue<string>,
    ruleId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<DataTypes.ConfirmationStructOutput>;

  effectsGet(
    ruleId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<DataTypes.RepChangeStructOutput[]>;

  effectsGetOf(
    ownerAddress: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<DataTypes.RepChangeStructOutput[]>;

  ruleAdd(
    rule: DataTypes.RuleStruct,
    effects: DataTypes.RepChangeStruct[],
    confirmation: DataTypes.ConfirmationStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ruleDisable(
    ruleId: PromiseOrValue<BigNumberish>,
    disabled: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ruleEffectsUpdate(
    ruleId: PromiseOrValue<BigNumberish>,
    effects: DataTypes.RepChangeStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ruleGet(
    ruleId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<DataTypes.RuleStructOutput>;

  ruleUpdateConditions(
    ruleId: PromiseOrValue<BigNumberish>,
    conditions: DataTypes.ConditionStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ruleUpdateConfirmation(
    ruleId: PromiseOrValue<BigNumberish>,
    confirmation: DataTypes.ConfirmationStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ruleUpdateURI(
    ruleId: PromiseOrValue<BigNumberish>,
    uri: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    conditionsGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<DataTypes.ConditionStructOutput[]>;

    conditionsGetOf(
      ownerAddress: PromiseOrValue<string>,
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<DataTypes.ConditionStructOutput[]>;

    confirmationGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<DataTypes.ConfirmationStructOutput>;

    confirmationGetOf(
      ownerAddress: PromiseOrValue<string>,
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<DataTypes.ConfirmationStructOutput>;

    effectsGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<DataTypes.RepChangeStructOutput[]>;

    effectsGetOf(
      ownerAddress: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<DataTypes.RepChangeStructOutput[]>;

    ruleAdd(
      rule: DataTypes.RuleStruct,
      effects: DataTypes.RepChangeStruct[],
      confirmation: DataTypes.ConfirmationStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ruleDisable(
      ruleId: PromiseOrValue<BigNumberish>,
      disabled: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    ruleEffectsUpdate(
      ruleId: PromiseOrValue<BigNumberish>,
      effects: DataTypes.RepChangeStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    ruleGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<DataTypes.RuleStructOutput>;

    ruleUpdateConditions(
      ruleId: PromiseOrValue<BigNumberish>,
      conditions: DataTypes.ConditionStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    ruleUpdateConfirmation(
      ruleId: PromiseOrValue<BigNumberish>,
      confirmation: DataTypes.ConfirmationStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    ruleUpdateURI(
      ruleId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Condition(address,uint256,string,bytes32)"(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: PromiseOrValue<BigNumberish> | null,
      repo?: null,
      id?: null
    ): ConditionEventFilter;
    Condition(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: PromiseOrValue<BigNumberish> | null,
      repo?: null,
      id?: null
    ): ConditionEventFilter;

    "Confirmation(address,uint256,string,bool,uint256)"(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: PromiseOrValue<BigNumberish> | null,
      ruling?: null,
      evidence?: null,
      witness?: null
    ): ConfirmationEventFilter;
    Confirmation(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: PromiseOrValue<BigNumberish> | null,
      ruling?: null,
      evidence?: null,
      witness?: null
    ): ConfirmationEventFilter;

    "RemovedConditions(address,uint256)"(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: PromiseOrValue<BigNumberish> | null
    ): RemovedConditionsEventFilter;
    RemovedConditions(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: PromiseOrValue<BigNumberish> | null
    ): RemovedConditionsEventFilter;

    "RemovedEffects(address,uint256)"(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: PromiseOrValue<BigNumberish> | null
    ): RemovedEffectsEventFilter;
    RemovedEffects(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: PromiseOrValue<BigNumberish> | null
    ): RemovedEffectsEventFilter;

    "Rule(address,uint256,bytes32,string,string,bool)"(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: PromiseOrValue<BigNumberish> | null,
      about?: null,
      affected?: null,
      uri?: null,
      negation?: null
    ): RuleEventFilter;
    Rule(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: PromiseOrValue<BigNumberish> | null,
      about?: null,
      affected?: null,
      uri?: null,
      negation?: null
    ): RuleEventFilter;

    "RuleDisabled(address,uint256,bool)"(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: null,
      disabled?: null
    ): RuleDisabledEventFilter;
    RuleDisabled(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: null,
      disabled?: null
    ): RuleDisabledEventFilter;

    "RuleEffect(address,uint256,string,int256)"(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: PromiseOrValue<BigNumberish> | null,
      domain?: null,
      value?: null
    ): RuleEffectEventFilter;
    RuleEffect(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: PromiseOrValue<BigNumberish> | null,
      domain?: null,
      value?: null
    ): RuleEffectEventFilter;

    "RuleRemoved(address,uint256)"(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: PromiseOrValue<BigNumberish> | null
    ): RuleRemovedEventFilter;
    RuleRemoved(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: PromiseOrValue<BigNumberish> | null
    ): RuleRemovedEventFilter;

    "RuleURI(address,uint256,string)"(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: null,
      uri?: null
    ): RuleURIEventFilter;
    RuleURI(
      originAddress?: PromiseOrValue<string> | null,
      ruleId?: null,
      uri?: null
    ): RuleURIEventFilter;
  };

  estimateGas: {
    conditionsGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    conditionsGetOf(
      ownerAddress: PromiseOrValue<string>,
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    confirmationGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    confirmationGetOf(
      ownerAddress: PromiseOrValue<string>,
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    effectsGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    effectsGetOf(
      ownerAddress: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ruleAdd(
      rule: DataTypes.RuleStruct,
      effects: DataTypes.RepChangeStruct[],
      confirmation: DataTypes.ConfirmationStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ruleDisable(
      ruleId: PromiseOrValue<BigNumberish>,
      disabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ruleEffectsUpdate(
      ruleId: PromiseOrValue<BigNumberish>,
      effects: DataTypes.RepChangeStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ruleGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ruleUpdateConditions(
      ruleId: PromiseOrValue<BigNumberish>,
      conditions: DataTypes.ConditionStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ruleUpdateConfirmation(
      ruleId: PromiseOrValue<BigNumberish>,
      confirmation: DataTypes.ConfirmationStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ruleUpdateURI(
      ruleId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    conditionsGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    conditionsGetOf(
      ownerAddress: PromiseOrValue<string>,
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    confirmationGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    confirmationGetOf(
      ownerAddress: PromiseOrValue<string>,
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    effectsGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    effectsGetOf(
      ownerAddress: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ruleAdd(
      rule: DataTypes.RuleStruct,
      effects: DataTypes.RepChangeStruct[],
      confirmation: DataTypes.ConfirmationStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ruleDisable(
      ruleId: PromiseOrValue<BigNumberish>,
      disabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ruleEffectsUpdate(
      ruleId: PromiseOrValue<BigNumberish>,
      effects: DataTypes.RepChangeStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ruleGet(
      ruleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ruleUpdateConditions(
      ruleId: PromiseOrValue<BigNumberish>,
      conditions: DataTypes.ConditionStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ruleUpdateConfirmation(
      ruleId: PromiseOrValue<BigNumberish>,
      confirmation: DataTypes.ConfirmationStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ruleUpdateURI(
      ruleId: PromiseOrValue<BigNumberish>,
      uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
