/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IStringStoreInterface extends utils.Interface {
  contractName: "IStringStore";
  functions: {
    "stringAdd(string,string)": FunctionFragment;
    "stringGet(string)": FunctionFragment;
    "stringGetIndex(string,uint256)": FunctionFragment;
    "stringGetIndexOf(address,string,uint256)": FunctionFragment;
    "stringGetOf(address,string)": FunctionFragment;
    "stringRemove(string,string)": FunctionFragment;
    "stringSet(string,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "stringAdd",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "stringGet", values: [string]): string;
  encodeFunctionData(
    functionFragment: "stringGetIndex",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stringGetIndexOf",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stringGetOf",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "stringRemove",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "stringSet",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "stringAdd", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stringGet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stringGetIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stringGetIndexOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stringGetOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stringRemove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stringSet", data: BytesLike): Result;

  events: {};
}

export interface IStringStore extends BaseContract {
  contractName: "IStringStore";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IStringStoreInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    stringAdd(
      key: string,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stringGet(key: string, overrides?: CallOverrides): Promise<[string]>;

    stringGetIndex(
      key: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    stringGetIndexOf(
      originAddress: string,
      key: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    stringGetOf(
      originAddress: string,
      key: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    stringRemove(
      key: string,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stringSet(
      key: string,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  stringAdd(
    key: string,
    value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stringGet(key: string, overrides?: CallOverrides): Promise<string>;

  stringGetIndex(
    key: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  stringGetIndexOf(
    originAddress: string,
    key: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  stringGetOf(
    originAddress: string,
    key: string,
    overrides?: CallOverrides
  ): Promise<string>;

  stringRemove(
    key: string,
    value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stringSet(
    key: string,
    value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    stringAdd(
      key: string,
      value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    stringGet(key: string, overrides?: CallOverrides): Promise<string>;

    stringGetIndex(
      key: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    stringGetIndexOf(
      originAddress: string,
      key: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    stringGetOf(
      originAddress: string,
      key: string,
      overrides?: CallOverrides
    ): Promise<string>;

    stringRemove(
      key: string,
      value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    stringSet(
      key: string,
      value: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    stringAdd(
      key: string,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stringGet(key: string, overrides?: CallOverrides): Promise<BigNumber>;

    stringGetIndex(
      key: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    stringGetIndexOf(
      originAddress: string,
      key: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    stringGetOf(
      originAddress: string,
      key: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    stringRemove(
      key: string,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stringSet(
      key: string,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    stringAdd(
      key: string,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stringGet(
      key: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stringGetIndex(
      key: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stringGetIndexOf(
      originAddress: string,
      key: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stringGetOf(
      originAddress: string,
      key: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    stringRemove(
      key: string,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stringSet(
      key: string,
      value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
